"""
JSW Motors — Competency & TNA Survey
Functional competencies derived from the JSW Motors Functional Scorecard (FY2026–FY2030).
Each function's competencies are aligned to their KPI areas.
"""

FUNCTIONS = {
    'sales_marketing': {
        'label': 'Sales & Marketing',
        'head_title': 'Chief Sales Officer / VP Sales & Marketing',
        'kpi_areas': ['Volume & Revenue', 'Channel & Dealer Management', 'Customer Experience',
                      'Digital Marketing & ROI', 'After-Sales Support'],
        'competencies': [
            {'code': 'SM01', 'name': 'Sales Volume & Retail Planning',
             'category': 'Technical', 'kpi_link': 'Retail Sales Volume / Wholesale Dispatch',
             'desc': 'Drive retail and wholesale dispatch targets; manage volume vs plan, dealer-wise allocation and monthly rolling forecast.'},
            {'code': 'SM02', 'name': 'Channel & Dealer Network Management',
             'category': 'Technical', 'kpi_link': 'Dealer Network Expansion / Dealer Satisfaction Index',
             'desc': 'Develop and operationalise dealer network; monitor DSI, manage dealer appointment, audit and performance reviews.'},
            {'code': 'SM03', 'name': 'Customer Experience & NPS Management',
             'category': 'Technical', 'kpi_link': 'CSAT/NPS / Lead Response Time / Retail-to-Booking Conversion',
             'desc': 'Drive customer satisfaction scores; manage enquiry-to-booking funnel; ensure sub-2-hour lead response SLA.'},
            {'code': 'SM04', 'name': 'Digital Marketing & Lead Generation',
             'category': 'Technical', 'kpi_link': 'Digital Lead Share % / EV Adoption Campaign Reach',
             'desc': 'Plan and execute SEO/SEM/social campaigns; track digital lead share %; manage EV awareness campaigns across metros.'},
            {'code': 'SM05', 'name': 'CRM & Sales Operations Analytics',
             'category': 'Technical', 'kpi_link': 'CRM Analytics / Pipeline Management / Conversion Rate',
             'desc': 'CRM platform proficiency; pipeline analytics, win-loss analysis, conversion optimisation and funnel reporting.'},
            {'code': 'SM06', 'name': 'EV Market Intelligence & Competitive Analysis',
             'category': 'Technical', 'kpi_link': 'Market Share (NEV) / Brand Awareness Score',
             'desc': 'India EV market trends, FAME II / PLI policy analysis, competitor product benchmarking and customer adoption barrier insights.'},
            {'code': 'SM07', 'name': 'Revenue & P&L Management',
             'category': 'Technical', 'kpi_link': 'Revenue vs Plan / Average Realisation per Unit',
             'desc': 'Manage revenue vs AOP; drive average realisation per unit; understand discount impact on contribution margin.'},
            {'code': 'SM08', 'name': 'Brand Management & Positioning',
             'category': 'Technical', 'kpi_link': 'Brand Awareness Score / Marketing ROI',
             'desc': 'Brand architecture management; drive unaided brand recall in target metros; manage marketing ROI and cost per lead.'},
            {'code': 'SM09', 'name': 'After-Sales & Service Market Management',
             'category': 'Technical', 'kpi_link': 'Service Market Penetration / Warranty Cost per Vehicle',
             'desc': 'Drive vehicles-in-field serviced at authorised network %; manage warranty cost per vehicle within targets.'},
            {'code': 'SM10', 'name': 'Sales Forecasting & MIS Reporting',
             'category': 'Technical', 'kpi_link': 'Sales Analytics / Dealer Dispatch MIS',
             'desc': 'Territory-wise analysis, conversion metrics, monthly forecast accuracy and variance commentary for management reviews.'},
            {'code': 'SM11', 'name': 'Commercial Acumen & Business Orientation',
             'category': 'Behavioral', 'kpi_link': 'Revenue / EBITDA Impact of Sales Decisions',
             'desc': 'Ability to connect sales activity to business outcomes; understand cost structure and impact of pricing decisions.'},
            {'code': 'SM12', 'name': 'Negotiation & Stakeholder Influence',
             'category': 'Behavioral', 'kpi_link': 'Channel Agreement Negotiation / Dealer Management',
             'desc': 'Negotiate channel agreements and pricing with dealers; manage trade-offs and influence without direct authority.'},
            {'code': 'SM13', 'name': 'Customer Orientation & Service Mindset',
             'category': 'Behavioral', 'kpi_link': 'CSAT / NPS / Customer Retention',
             'desc': 'Genuine focus on understanding and meeting customer needs; treating every interaction as a brand moment.'},
            {'code': 'SM14', 'name': 'Data-Driven Decision Making',
             'category': 'Behavioral', 'kpi_link': 'Digital Analytics / Conversion Optimisation',
             'desc': 'Using CRM data, market analytics and territory insights to prioritise leads and drive strategy.'},
            {'code': 'SM15', 'name': 'Executive Communication & Storytelling',
             'category': 'Behavioral', 'kpi_link': 'Board Presentations / Leadership Reviews',
             'desc': 'Synthesising complex sales data into compelling narratives; presenting confidently to senior leadership.'},
        ]
    },

    'engineering': {
        'label': 'Engineering',
        'head_title': 'Chief Engineering Officer / VP Engineering',
        'kpi_areas': ['Vehicle Performance & Reliability', 'Product Development Milestones',
                      'Cost Engineering', 'Quality (Engineering Origin)', 'Sustainability'],
        'competencies': [
            {'code': 'EN01', 'name': 'Vehicle Range & Performance Engineering',
             'category': 'Technical', 'kpi_link': 'Certified ARAI Range / 0-100 km/h Performance vs Spec',
             'desc': 'Ensure certified range and acceleration performance meet or exceed design targets for each platform variant.'},
            {'code': 'EN02', 'name': 'Crashworthiness & Functional Safety Engineering',
             'category': 'Technical', 'kpi_link': 'Crash Test Rating (NCAP) / ISO 26262',
             'desc': 'Manage NCAP (Bharat/Global) safety engineering; understand ASIL ratings and ISO 26262 functional safety for EV.'},
            {'code': 'EN03', 'name': 'DVP / Design Validation Management',
             'category': 'Technical', 'kpi_link': 'Engineering DVP Completion % / Design Freeze Schedule',
             'desc': 'Plan and track Design Validation Plans; ensure all milestones completed on schedule before SOP.'},
            {'code': 'EN04', 'name': 'NVH Engineering & Benchmarking',
             'category': 'Technical', 'kpi_link': 'NVH Performance Index vs Benchmark',
             'desc': 'Measure and manage noise-vibration-harshness performance; benchmark against segment competitors.'},
            {'code': 'EN05', 'name': 'BOM Cost Engineering & Value Engineering',
             'category': 'Technical', 'kpi_link': 'BOM Cost vs Target / Value Engineering Savings',
             'desc': 'Manage actual BOM cost vs target cost per vehicle; lead VE/VA initiatives to deliver annual savings.'},
            {'code': 'EN06', 'name': 'DFMEA & Engineering Quality Systems',
             'category': 'Technical', 'kpi_link': 'DFMEA Coverage % / Field Defect Rate (Eng Origin)',
             'desc': 'Drive DFMEA coverage for all critical systems; minimise field defect rate attributable to engineering decisions.'},
            {'code': 'EN07', 'name': 'Software / ECU Engineering & Quality',
             'category': 'Technical', 'kpi_link': 'ECU/Software Defect Density / OTA Readiness',
             'desc': 'Manage ECU software defect density at SOP; ensure vehicle variants are OTA-ready per product plan.'},
            {'code': 'EN08', 'name': 'Homologation & Regulatory Compliance',
             'category': 'Technical', 'kpi_link': 'Homologation Clearance On Time / AIS/RoHS Compliance',
             'desc': 'Obtain all regulatory clearances before SOP; maintain 100% RoHS/AIS parts compliance.'},
            {'code': 'EN09', 'name': 'Platform Architecture & Component Reuse',
             'category': 'Technical', 'kpi_link': 'Platform Reuse Index / CAPEX Efficiency',
             'desc': 'Drive component sharing across platforms; maximise reuse index to reduce tooling CAPEX and NRE costs.'},
            {'code': 'EN10', 'name': 'Sustainability & Materials Engineering',
             'category': 'Technical', 'kpi_link': 'Recyclability Index / RoHS / Hazardous Material Compliance',
             'desc': 'Ensure end-of-life recyclability targets per platform; maintain compliance with hazardous material standards.'},
            {'code': 'EN11', 'name': 'Analytical Problem Solving & Root Cause Analysis',
             'category': 'Behavioral', 'kpi_link': 'Field Defect Rate Reduction / Quality Improvement',
             'desc': 'Apply 8D, A3, FTA and structured problem-solving to engineering defects and design failures.'},
            {'code': 'EN12', 'name': 'Cross-Functional Engineering Collaboration',
             'category': 'Behavioral', 'kpi_link': 'DVP Schedule / BOM Cost Management',
             'desc': 'Work effectively with Manufacturing, Quality, Procurement and Test teams to deliver on program milestones.'},
            {'code': 'EN13', 'name': 'CAPEX & Engineering Budget Discipline',
             'category': 'Behavioral', 'kpi_link': 'CAPEX vs Approved Budget',
             'desc': 'Manage tooling and validation spend within sanctioned budget; raise early flags on cost overruns.'},
            {'code': 'EN14', 'name': 'Technical Communication & Stakeholder Reporting',
             'category': 'Behavioral', 'kpi_link': 'Leadership Reviews / Engineering Gate Reviews',
             'desc': 'Present DVP status, defect analysis and BOM cost data clearly to engineering leadership and ExCo.'},
        ]
    },

    'new_product_dev': {
        'label': 'New Product Development',
        'head_title': 'Chief Product Officer / VP NPD',
        'kpi_areas': ['Product Pipeline & Launch', 'Customer & Market Fit',
                      'Program Management & Budget', 'Technology & Future Readiness'],
        'competencies': [
            {'code': 'NP01', 'name': 'Product Launch & SOP Milestone Management',
             'category': 'Technical', 'kpi_link': 'SOP Milestone Achievement % / Concept-to-SOP Cycle Time',
             'desc': 'Drive Start of Production gates on planned date; manage concept-to-SOP cycle time reduction year-on-year.'},
            {'code': 'NP02', 'name': 'Prototype Build & Schedule Management',
             'category': 'Technical', 'kpi_link': 'Prototype Build Schedule Adherence %',
             'desc': 'Plan and track all prototype build milestones; ensure builds adhere to development program schedule.'},
            {'code': 'NP03', 'name': 'Program Budget & Financial Accountability',
             'category': 'Technical', 'kpi_link': 'Program Budget Adherence % / CAPEX Allocation',
             'desc': 'Manage individual program cost vs approved budget; drive cost consciousness across NPD activities.'},
            {'code': 'NP04', 'name': 'Voice of Customer (VoC) Integration',
             'category': 'Technical', 'kpi_link': 'VoC Integration Score / Price-to-Value Positioning',
             'desc': 'Ensure customer research themes are addressed in product concept; validate price-to-value positioning externally.'},
            {'code': 'NP05', 'name': 'Competitive Benchmarking & Feature Planning',
             'category': 'Technical', 'kpi_link': 'Competitive Feature Parity Index',
             'desc': 'Benchmark JSW Motors features vs 3 top competitors; plan feature roadmap to achieve parity or better at launch.'},
            {'code': 'NP06', 'name': 'OTA & Connected Vehicle Platform Management',
             'category': 'Technical', 'kpi_link': 'EV Software / OTA Capability Readiness %',
             'desc': 'Ensure vehicle variants are OTA-ready at launch; coordinate with IT/Engineering on connected vehicle platform.'},
            {'code': 'NP07', 'name': 'ADAS & Advanced Technology Integration',
             'category': 'Technical', 'kpi_link': 'ADAS Feature Integration (L1/L2/L2+) per Model',
             'desc': 'Plan ADAS feature integration per product plan; manage technology readiness and supplier qualification.'},
            {'code': 'NP08', 'name': 'Localisation Planning at SOP',
             'category': 'Technical', 'kpi_link': 'Localisation Level at SOP / Local Content %',
             'desc': 'Drive domestic content % targets at vehicle launch; coordinate with Procurement on vendor qualification timelines.'},
            {'code': 'NP09', 'name': 'IP Strategy & Patent Management',
             'category': 'Technical', 'kpi_link': 'IP Filed (Patents) / Innovation Pipeline',
             'desc': 'Identify patentable innovations in product development; file and manage IP pipeline across platforms.'},
            {'code': 'NP10', 'name': 'Risk Management in Product Programs',
             'category': 'Technical', 'kpi_link': 'Risk Register Coverage / ECR Resolution TAT',
             'desc': 'Maintain risk register with mitigation plans for all active programs; resolve Engineering Change Requests within SLA.'},
            {'code': 'NP11', 'name': 'Strategic Product Thinking',
             'category': 'Behavioral', 'kpi_link': 'Product Pipeline / Market Share',
             'desc': 'Think beyond individual programs to portfolio strategy; connect product decisions to market share and revenue targets.'},
            {'code': 'NP12', 'name': 'Cross-Functional Program Leadership',
             'category': 'Behavioral', 'kpi_link': 'SOP Schedule / Program Budget',
             'desc': 'Lead diverse cross-functional teams (Engineering, Manufacturing, Procurement, Sales) to deliver programs on time.'},
            {'code': 'NP13', 'name': 'Innovation & Technology Readiness Mindset',
             'category': 'Behavioral', 'kpi_link': 'OTA Readiness / ADAS Integration / IP Filing',
             'desc': 'Proactively explore software-defined vehicle trends; champion innovation and technology adoption across NPD.'},
        ]
    },

    'finance': {
        'label': 'Finance',
        'head_title': 'CFO / VP Finance',
        'kpi_areas': ['P&L Management', 'CAPEX & Working Capital', 'Business Partnering & Controls',
                      'Cost Optimisation', 'Investor & Funding'],
        'competencies': [
            {'code': 'FN01', 'name': 'P&L Management & Revenue Planning',
             'category': 'Technical', 'kpi_link': 'Revenue vs AOP / EBITDA / Gross Margin / SGA%',
             'desc': 'Own P&L from revenue to EBITDA; manage gross margin improvement, SGA as % of revenue within targets.'},
            {'code': 'FN02', 'name': 'CAPEX Planning & Budget Control',
             'category': 'Technical', 'kpi_link': 'CAPEX vs Budget (₹ Cr)',
             'desc': 'Manage cumulative CAPEX vs sanctioned budget; coordinate with plant and project teams for spend authorisation.'},
            {'code': 'FN03', 'name': 'Working Capital & Cash Flow Management',
             'category': 'Technical', 'kpi_link': 'Working Capital Days / Cash & Liquidity Cover / DSI',
             'desc': 'Optimise net WC cycle; manage cash/liquidity cover months; drive DSI (Days Sales of Inventory) reduction.'},
            {'code': 'FN04', 'name': 'Financial Reporting, MIS & Board Packs',
             'category': 'Technical', 'kpi_link': 'MIS & Board Reporting On Time %',
             'desc': 'Ensure 100% on-time delivery of board and investor packs; maintain accuracy of all financial disclosures.'},
            {'code': 'FN05', 'name': 'FP&A & Quarterly Forecast Accuracy',
             'category': 'Technical', 'kpi_link': 'Budget Variance Accuracy / Forecast vs Actual',
             'desc': 'Manage rolling quarterly forecasts within variance targets; conduct variance analysis and corrective planning.'},
            {'code': 'FN06', 'name': 'Statutory & Tax Compliance',
             'category': 'Technical', 'kpi_link': 'Statutory Compliance — Zero Lapses',
             'desc': 'Ensure zero statutory/tax filing lapses; manage ROC, GST, TDS and other regulatory compliance calendars.'},
            {'code': 'FN07', 'name': 'Internal Controls & Audit Management',
             'category': 'Technical', 'kpi_link': 'High-Risk Audit Findings Closed in 90 Days',
             'desc': 'Design and maintain internal controls; drive closure of high-risk audit observations within 90 days.'},
            {'code': 'FN08', 'name': 'Cost Reduction & Optimisation Programs',
             'category': 'Technical', 'kpi_link': 'Cost Reduction Savings (₹ Cr)',
             'desc': 'Lead cross-functional cost reduction initiatives; track and deliver annual savings targets vs plan.'},
            {'code': 'FN09', 'name': 'Treasury & Fund Management',
             'category': 'Technical', 'kpi_link': 'Fundraising / Debt Drawdown / Credit Rating',
             'desc': 'Manage fundraising, debt drawdown vs plan; optimise treasury returns; maintain and improve credit ratings.'},
            {'code': 'FN10', 'name': 'Vendor Payment Terms & Commercial Optimisation',
             'category': 'Technical', 'kpi_link': 'Vendor Payment Terms Optimisation (Days)',
             'desc': 'Negotiate extended creditor days with vendors; manage dynamic discounting and supply chain finance programs.'},
            {'code': 'FN11', 'name': 'Business Partnering & Decision Support',
             'category': 'Behavioral', 'kpi_link': 'Cross-Functional Finance Advisory',
             'desc': 'Act as a trusted advisor to function heads; translate financial data into actionable business recommendations.'},
            {'code': 'FN12', 'name': 'Analytical Rigour & Financial Modelling',
             'category': 'Behavioral', 'kpi_link': 'Forecast Accuracy / Scenario Analysis',
             'desc': 'Build robust financial models; apply scenario analysis and sensitivity testing to support strategic decisions.'},
            {'code': 'FN13', 'name': 'Compliance Mindset & Zero-Error Culture',
             'category': 'Behavioral', 'kpi_link': 'Statutory Zero Lapses / Payroll Accuracy',
             'desc': 'Internalised belief in zero-error financial compliance; proactively identify and close compliance gaps.'},
        ]
    },

    'hr': {
        'label': 'HR',
        'head_title': 'CHRO / VP Human Resources',
        'kpi_areas': ['Talent Acquisition', 'Capability Development', 'Engagement & Retention',
                      'HR Operations & Compliance', 'Culture & Inclusion'],
        'competencies': [
            {'code': 'HR01', 'name': 'Talent Acquisition & Critical Role Fulfilment',
             'category': 'Technical', 'kpi_link': 'Critical Role Fulfilment ≤90 Days / Blue Collar Ramp Hiring',
             'desc': 'Fill Band 1-4 critical roles within 90 days; manage blue collar on-boarding to production ramp schedule.'},
            {'code': 'HR02', 'name': 'Learning & Development Execution',
             'category': 'Technical', 'kpi_link': 'Training Man-Days per Employee / Learning ROI',
             'desc': 'Deliver 8–10 training man-days/employee annually; measure and report Learning ROI per program.'},
            {'code': 'HR03', 'name': 'Skill Centre & Academy Operations',
             'category': 'Technical', 'kpi_link': 'Skill Centre Operationalisation % / Manufacturing Tech Capability Score',
             'desc': 'Operationalise and certify 8 skill centres; drive manufacturing tech capability scores in platform assessments.'},
            {'code': 'HR04', 'name': 'Dealer & After-Sales Technician Capability',
             'category': 'Technical', 'kpi_link': 'Dealer Tech Certification % / After-Sales Service Technician Readiness',
             'desc': 'Certify dealer technicians on EV platform; ensure service techs at L1/L2 certification before market entry.'},
            {'code': 'HR05', 'name': 'Employee Engagement & Culture Building',
             'category': 'Technical', 'kpi_link': 'Employee Engagement Score / Culture Alignment Score',
             'desc': 'Design and action annual engagement surveys (Gallup/AON); drive culture pulse score improvements quarterly.'},
            {'code': 'HR06', 'name': 'Attrition & Retention Management',
             'category': 'Technical', 'kpi_link': 'Overall Attrition % / Critical Talent Attrition %',
             'desc': 'Monitor and manage overall and critical talent attrition; design targeted retention programs for high-potentials.'},
            {'code': 'HR07', 'name': 'HR Compliance & Labour Law Management',
             'category': 'Technical', 'kpi_link': 'HR Compliance Zero Violations / POSH Resolution TAT',
             'desc': 'Maintain zero labour law violations; resolve POSH complaints within 30-day SLA; manage ICC processes.'},
            {'code': 'HR08', 'name': 'Payroll Accuracy & HR Operations',
             'category': 'Technical', 'kpi_link': 'Payroll Accuracy % / HRMS Data Integrity',
             'desc': 'Ensure error-free payroll for 99.8%+ employees; maintain HRMS master data accuracy.'},
            {'code': 'HR09', 'name': 'Diversity, Equity & Inclusion Programs',
             'category': 'Technical', 'kpi_link': 'Diversity Hire % (Women / PwD / Other)',
             'desc': 'Drive diversity hire % targets; design inclusive hiring pipelines and gender balance programs.'},
            {'code': 'HR10', 'name': 'Leadership Pipeline & Succession Planning',
             'category': 'Technical', 'kpi_link': 'Leadership Pipeline Readiness / Internal Mobility Fill Rate',
             'desc': 'Identify successors for critical roles; manage Hi-Po programs; drive internal mobility fill rate targets.'},
            {'code': 'HR11', 'name': 'HR Business Partnering & Advisory',
             'category': 'Behavioral', 'kpi_link': 'People Strategy Execution / Manager Effectiveness',
             'desc': 'Coach leaders on people decisions; translate business strategy into HR interventions across functions.'},
            {'code': 'HR12', 'name': 'Change Management & OD',
             'category': 'Behavioral', 'kpi_link': 'Culture Alignment / Organisational Effectiveness',
             'desc': 'Lead organisational design changes; manage change with ADKAR methodology for culture transformation.'},
            {'code': 'HR13', 'name': 'Data-Driven HR Decision Making',
             'category': 'Behavioral', 'kpi_link': 'Attrition Prediction / Engagement Analytics',
             'desc': 'Use HR analytics, attrition predictors and engagement data to drive proactive talent interventions.'},
        ]
    },

    'procurement': {
        'label': 'Procurement & Localisation',
        'head_title': 'VP Procurement / Head Supply Chain Localisation',
        'kpi_areas': ['Localisation & Supply Base', 'Cost & Commercial',
                      'Supplier Quality (SQA)', 'Risk & Resilience'],
        'competencies': [
            {'code': 'PR01', 'name': 'Localisation Strategy & Execution',
             'category': 'Technical', 'kpi_link': 'Domestic Localisation % / Import Duty Savings',
             'desc': 'Drive domestic BOM % from 45% to 78% by FY30; manage vendor development for local supply; track import duty savings.'},
            {'code': 'PR02', 'name': 'Supplier Identification & Development',
             'category': 'Technical', 'kpi_link': 'Supplier Base Development / New Vendor Qualification TAT',
             'desc': 'Build Tier-1 supplier base from 80 to 260 vendors; manage qualification from RFQ to approval within TAT.'},
            {'code': 'PR03', 'name': 'Cost Management & Commercial Negotiations',
             'category': 'Technical', 'kpi_link': 'Material Cost % of Revenue / Cost Reduction vs Prior Year',
             'desc': 'Drive material cost % from 72% to 62% of revenue; deliver year-on-year cost reduction savings targets.'},
            {'code': 'PR04', 'name': 'Long-Term Agreement & Contract Management',
             'category': 'Technical', 'kpi_link': 'LTA Coverage % / Price Index Variance',
             'desc': 'Increase annual spend under multi-year LTAs; manage PPV vs commodity benchmark within tolerance.'},
            {'code': 'PR05', 'name': 'Supplier Quality Assurance (SQA & PPAP)',
             'category': 'Technical', 'kpi_link': 'Supplier PPM / PPAP First-Time Pass %',
             'desc': 'Drive supplier PPM from <500 to <120; achieve 90% PPAP first-time pass rate by FY30.'},
            {'code': 'PR06', 'name': 'Vendor Audit & CAPA Management',
             'category': 'Technical', 'kpi_link': 'Supplier Audit Score / CAPA Closure Rate',
             'desc': 'Conduct bi-annual supplier audits; ensure average audit score improvement; close CAPAs within SLA.'},
            {'code': 'PR07', 'name': 'Supply Chain Risk & Resilience Management',
             'category': 'Technical', 'kpi_link': 'Single-Source Dependency % / Supply Continuity',
             'desc': 'Reduce single-source dependency from 25% to <10% of spend; ensure zero production stoppages from supply failure.'},
            {'code': 'PR08', 'name': 'Spend Analytics & Procurement Reporting',
             'category': 'Technical', 'kpi_link': 'Price Index Variance / Procurement MIS',
             'desc': 'Maintain spend analytics dashboards; report PPV vs commodity benchmark; supply base scorecards monthly.'},
            {'code': 'PR09', 'name': 'ESG & Sustainable Procurement',
             'category': 'Technical', 'kpi_link': 'ESG-Compliant Suppliers %',
             'desc': 'Drive ESG-compliant supplier % from 50% to 92%; manage conflict minerals, responsible sourcing standards.'},
            {'code': 'PR10', 'name': 'EV Component Technical Understanding',
             'category': 'Technical', 'kpi_link': 'Localisation of EV Components (Cells, BMS, Motors, Inverters)',
             'desc': 'Understand technical specs of key EV components being procured; liaise with Engineering on qualification criteria.'},
            {'code': 'PR11', 'name': 'Negotiation & Supplier Relationship Management',
             'category': 'Behavioral', 'kpi_link': 'Cost Reduction / LTA Coverage',
             'desc': 'Negotiate effectively on price, quality and delivery; build long-term partnerships with strategic suppliers.'},
            {'code': 'PR12', 'name': 'Analytical Thinking & Cost Modelling',
             'category': 'Behavioral', 'kpi_link': 'Should-Costing / TCO Analysis',
             'desc': 'Apply should-costing, TCO analysis and cost build-up models to procurement decisions.'},
            {'code': 'PR13', 'name': 'Ethical Standards & Procurement Integrity',
             'category': 'Behavioral', 'kpi_link': 'Governance / Anti-Corruption',
             'desc': 'Maintain objectivity in vendor selection; zero conflicts of interest; transparent dealing with all suppliers.'},
        ]
    },

    'scm_logistics': {
        'label': 'SCM & Logistics',
        'head_title': 'VP SCM / Head Supply Chain & Logistics',
        'kpi_areas': ['Demand & Production Planning', 'Inventory & Warehousing',
                      'Logistics & Delivery', 'Spare Parts & After-Market', 'Digital & Sustainability'],
        'competencies': [
            {'code': 'SC01', 'name': 'Demand Planning & Forecast Accuracy',
             'category': 'Technical', 'kpi_link': 'Demand Forecast Accuracy % (MAPE) / S&OP Cycle Adherence',
             'desc': 'Manage 3-month rolling MAPE-based demand forecast; drive forecast accuracy from 80% to 90% by FY30.'},
            {'code': 'SC02', 'name': 'Production Planning & Schedule Adherence',
             'category': 'Technical', 'kpi_link': 'Production Plan vs Actual % / MES Coordination',
             'desc': 'Drive production plan adherence from 90% to 97%; coordinate with manufacturing on daily and weekly schedules.'},
            {'code': 'SC03', 'name': 'S&OP Process Management',
             'category': 'Technical', 'kpi_link': 'S&OP Cycle Adherence / Cross-Functional Alignment',
             'desc': 'Conduct monthly S&OP meetings on schedule with all required inputs; maintain cross-functional alignment.'},
            {'code': 'SC04', 'name': 'Finished Goods Inventory Management',
             'category': 'Technical', 'kpi_link': 'FG Inventory — Dealer Network (Days)',
             'desc': 'Optimise FG inventory at dealer network from 20 to 12 days of retail; prevent excess and ageing stock.'},
            {'code': 'SC05', 'name': 'Raw Material Inventory & Warehouse Operations',
             'category': 'Technical', 'kpi_link': 'RM Inventory Days / Inventory Accuracy / Warehouse Utilisation',
             'desc': 'Manage plant RM inventory within targets; maintain perpetual inventory accuracy at 99%+; optimise warehouse space.'},
            {'code': 'SC06', 'name': 'Logistics & Dispatch OTIF Management',
             'category': 'Technical', 'kpi_link': 'Vehicle Dispatch OTIF % / Dealer Delivery Lead Time',
             'desc': 'Drive dispatch OTIF from 90% to 96%; reduce plant-to-dealer lead time from <10 to <5 days by FY30.'},
            {'code': 'SC07', 'name': 'Freight Cost Optimization',
             'category': 'Technical', 'kpi_link': 'Outbound Freight Cost per Unit (₹)',
             'desc': 'Drive outbound freight cost per unit from ₹12,000 to ₹8,000; manage carrier contracts and route optimisation.'},
            {'code': 'SC08', 'name': 'Spare Parts & After-Market Supply Management',
             'category': 'Technical', 'kpi_link': 'Spare Parts First Fill Rate / Back-order Rate',
             'desc': 'Achieve 95% spare parts first fill rate; reduce back-order rate below 4% across SKU portfolio.'},
            {'code': 'SC09', 'name': 'ERP / Digital SCM Systems Management',
             'category': 'Technical', 'kpi_link': 'ERP/SCM System Uptime % / Digital Tools Adoption',
             'desc': 'Maintain 99.9% ERP/SCM system uptime; drive digital tools adoption across planning and logistics teams.'},
            {'code': 'SC10', 'name': 'Transit Quality & Damage Prevention',
             'category': 'Technical', 'kpi_link': 'Transit Damage Rate (PPM) / Vehicle Protection Protocols',
             'desc': 'Reduce vehicle transit damage PPM from <800 to <200; manage packaging and carrier quality protocols.'},
            {'code': 'SC11', 'name': 'Cross-Functional S&OP & Planning Coordination',
             'category': 'Behavioral', 'kpi_link': 'S&OP Alignment / Forecast Accuracy',
             'desc': 'Align Sales, Manufacturing, Finance and Procurement in S&OP; resolve conflicts and drive consensus decisions.'},
            {'code': 'SC12', 'name': 'Supply Chain Analytics & Data-Driven Decisions',
             'category': 'Behavioral', 'kpi_link': 'Inventory Optimisation / Cost Reduction',
             'desc': 'Use data to drive inventory, logistics and demand decisions; apply statistical tools to reduce variability.'},
            {'code': 'SC13', 'name': 'Resilience & Escalation Management',
             'category': 'Behavioral', 'kpi_link': 'Supply Continuity / Production Stop Prevention',
             'desc': 'Proactively manage supply risks; escalate and resolve disruptions before they impact production.'},
        ]
    },

    'it_digital': {
        'label': 'IT & Digital',
        'head_title': 'CIO / VP IT & Digital',
        'kpi_areas': ['Systems & Infrastructure', 'Digital Transformation',
                      'Dealer & Customer Digital', 'Governance & Compliance'],
        'competencies': [
            {'code': 'IT01', 'name': 'Core IT Infrastructure & Systems Uptime',
             'category': 'Technical', 'kpi_link': 'Core Systems Uptime % (ERP, MES, HRMS) / SLA Compliance',
             'desc': 'Maintain 99.9% uptime for ERP, MES, HRMS; manage IT service desk SLA compliance by ticket priority.'},
            {'code': 'IT02', 'name': 'ERP Implementation & Digital Transformation',
             'category': 'Technical', 'kpi_link': 'ERP Go-Live Milestone / Phase Completion',
             'desc': 'Drive ERP go-live milestones (Phase 1→Full); manage change management and business readiness activities.'},
            {'code': 'IT03', 'name': 'MES Integration & Manufacturing IT',
             'category': 'Technical', 'kpi_link': 'MES Integration — Plant Coverage % / IIoT',
             'desc': 'Connect all production lines to MES from 40% to 100%; integrate IIoT sensors and shop floor data systems.'},
            {'code': 'IT04', 'name': 'Connected Vehicle & OTA Platform Management',
             'category': 'Technical', 'kpi_link': 'Connected Vehicle Platform Readiness / OTA % Models Covered',
             'desc': 'Deliver telematics/OTA platform from 30% to 100% model coverage; manage connected vehicle data architecture.'},
            {'code': 'IT05', 'name': 'Cybersecurity & Threat Management',
             'category': 'Technical', 'kpi_link': 'Cybersecurity Incidents (P1/P2) — Zero Target',
             'desc': 'Prevent all P1/P2 cybersecurity incidents; manage CISO governance, penetration testing and security operations.'},
            {'code': 'IT06', 'name': 'Data Privacy & DPDP Compliance',
             'category': 'Technical', 'kpi_link': 'DPDP / Data Privacy Compliance % / IT Audit Findings',
             'desc': 'Ensure 100% compliance with India DPDP Act; manage data handling, consent and breach response protocols.'},
            {'code': 'IT07', 'name': 'Dealer Management System (DMS) Operations',
             'category': 'Technical', 'kpi_link': 'DMS Adoption % / Digital Lead Processing TAT',
             'desc': 'Drive DMS adoption from 70% to 99% of dealers; ensure digital lead processing TAT within 1-hour SLA.'},
            {'code': 'IT08', 'name': 'Data Analytics & Business Intelligence',
             'category': 'Technical', 'kpi_link': 'Data Platform / Analytics Adoption % by Functions',
             'desc': 'Drive self-service dashboard adoption across functions from 30% to 80%; build data platform capabilities.'},
            {'code': 'IT09', 'name': 'IT CAPEX Planning & Budget Control',
             'category': 'Technical', 'kpi_link': 'IT CAPEX vs Approved Budget',
             'desc': 'Manage IT CAPEX spend within sanctioned budget; govern project prioritisation and spend approval process.'},
            {'code': 'IT10', 'name': 'Business Continuity & Disaster Recovery',
             'category': 'Technical', 'kpi_link': 'RTO Adherence in DR Drills / Software Licence Compliance',
             'desc': 'Achieve 96% RTO adherence in bi-annual DR drills; maintain 100% software licence compliance.'},
            {'code': 'IT11', 'name': 'IT-Business Alignment & Solution Design',
             'category': 'Behavioral', 'kpi_link': 'Digital Adoption / Business Process Improvement',
             'desc': 'Translate business requirements into scalable IT solutions; bridge gap between IT capabilities and business needs.'},
            {'code': 'IT12', 'name': 'Vendor & Technology Evaluation',
             'category': 'Behavioral', 'kpi_link': 'IT Vendor Management / Proof-of-Concept Management',
             'desc': 'Run structured RFP processes; manage vendor scoring, POC evaluation and TCO analysis for IT decisions.'},
            {'code': 'IT13', 'name': 'Continuous Learning & Technology Agility',
             'category': 'Behavioral', 'kpi_link': 'Emerging Technology Adoption / AI/ML / Cloud',
             'desc': 'Self-driven upskilling on emerging technologies (AI/ML, cloud, IIoT); stay current and apply to business context.'},
        ]
    },

    'manufacturing': {
        'label': 'Manufacturing',
        'head_title': 'COO / VP Manufacturing',
        'kpi_areas': ['Plant Readiness & Ramp', 'Production Volume & Efficiency',
                      'Quality', 'Cost', 'Safety & Environment'],
        'competencies': [
            {'code': 'MF01', 'name': 'Plant Readiness & Commissioning Management',
             'category': 'Technical', 'kpi_link': 'Plant Readiness Index / PPAP Sign-Off / CAPEX Commissioning',
             'desc': 'Drive plant readiness index to 95%+; ensure all lines achieve PPAP sign-off before SOP; manage commissioning milestones.'},
            {'code': 'MF02', 'name': 'Production Volume & Capacity Planning',
             'category': 'Technical', 'kpi_link': 'Volume Production vs Plan % / Installed Capacity Utilisation',
             'desc': 'Drive production plan adherence from 90% to 97%; scale installed capacity utilisation from 40% to 92% by FY30.'},
            {'code': 'MF03', 'name': 'OEE Optimisation & Equipment Effectiveness',
             'category': 'Technical', 'kpi_link': 'Overall Equipment Effectiveness (OEE %)',
             'desc': 'Drive OEE from 62% to 85% through availability, performance and quality improvements; lead TPM implementation.'},
            {'code': 'MF04', 'name': 'Manufacturing Process Engineering & Throughput',
             'category': 'Technical', 'kpi_link': 'Throughput Time (Hours/Vehicle)',
             'desc': 'Reduce vehicle assembly throughput time from 28 to 18 hours; drive cycle time reduction and line rebalancing.'},
            {'code': 'MF05', 'name': 'Quality Management (DPU, FTT, Warranty PPM)',
             'category': 'Technical', 'kpi_link': 'DPU / First Time Through % / Warranty PPM',
             'desc': 'Drive DPU from <1.8 to <0.6; achieve FTT 93%+; reduce plant-attributable warranty PPM from <400 to <110.'},
            {'code': 'MF06', 'name': 'Manufacturing Cost Control & Efficiency',
             'category': 'Technical', 'kpi_link': 'Manufacturing Cost per Unit (₹ Lakh) / Scrap & Rework Cost',
             'desc': 'Reduce manufacturing cost per unit from ₹8.5L to ₹5.8L; manage scrap and rework cost annually.'},
            {'code': 'MF07', 'name': 'Energy Management & Environmental Compliance',
             'category': 'Technical', 'kpi_link': 'Energy Cost per Unit / Environmental Non-Conformances / Water Intensity',
             'desc': 'Drive energy cost per unit from ₹3,500 to ₹2,200; achieve zero environmental non-conformances; manage water intensity.'},
            {'code': 'MF08', 'name': 'EHS & Safety Leadership (LTIFR)',
             'category': 'Technical', 'kpi_link': 'LTIFR / Near-Miss Reporting Rate',
             'desc': 'Drive LTIFR from <0.8 to <0.3; build near-miss reporting culture (>9 per 100 employees); manage ISO 45001 compliance.'},
            {'code': 'MF09', 'name': 'EV Assembly & Powertrain Manufacturing Knowledge',
             'category': 'Technical', 'kpi_link': 'EV Product Quality / Battery Module Assembly / HV Safety',
             'desc': 'Understand EV assembly sequence, battery module processes, HV safety protocols and LOTO on high-voltage lines.'},
            {'code': 'MF10', 'name': 'Lean Manufacturing & Continuous Improvement (Kaizen)',
             'category': 'Technical', 'kpi_link': 'OEE Improvement / Scrap Reduction / Kaizen Participation',
             'desc': 'Lead Kaizen, 5S and waste elimination programs; drive VSM-based improvements across all production shops.'},
            {'code': 'MF11', 'name': 'Safety-First Leadership & Culture',
             'category': 'Behavioral', 'kpi_link': 'LTIFR / Near-Miss Reporting / Safety Culture Index',
             'desc': 'Champion zero-harm safety culture; speak up on unsafe conditions; hold team accountable to safety standards.'},
            {'code': 'MF12', 'name': 'Production Ownership & Accountability',
             'category': 'Behavioral', 'kpi_link': 'Volume vs Plan / OEE / Quality KPIs',
             'desc': 'Own shift production targets; escalate issues proactively; never deflect responsibility when output is at risk.'},
            {'code': 'MF13', 'name': 'Team Management & Shift Leadership',
             'category': 'Behavioral', 'kpi_link': 'Workforce Productivity / Engagement / Cross-Shift Communication',
             'desc': 'Manage blue and white collar teams across shifts; ensure structured handover communication and team accountability.'},
        ]
    },
}


SURVEY_META = {
    'functional-head': {
        'title': 'Functional Head Competency Prioritisation Survey',
        'subtitle': 'Rate competency importance, select your Top 10, and set Day-1 readiness levels',
        'icon': '📝',
        'color': '#1A2D5A',
    },
    'self-assessment': {
        'title': 'Employee Competency Self-Assessment',
        'subtitle': 'Rate your current proficiency level against each competency for your function',
        'icon': '👤',
        'color': '#2E4B8F',
    },
}

PROFICIENCY_LEVELS = [
    (1, 'Awareness', 'Knows the concept; cannot apply independently'),
    (2, 'Basic', 'Can perform with guidance and supervision'),
    (3, 'Practitioner', 'Applies independently; meets expectations'),
    (4, 'Advanced', 'Applies with mastery; coaches others'),
    (5, 'Expert', 'Sets standards; recognised as subject authority'),
]

IMPORTANCE_LEVELS = [
    (1, 'Not Relevant'),
    (2, 'Nice to Have'),
    (3, 'Important'),
    (4, 'Very Important'),
    (5, 'Business Critical'),
]
